### PR TITLE
Handle newly-introduced types.Alias type

### PR DESCRIPTION
**Pull request by yuxincs**
Go 1.22 [1] introduces a proper `types.Alias` type for type aliases. This PR adds handling (by simply unwrapping alias node - effectively restoring previous behavior) for such a type.

Further simplification and refactors will be in future PRs.

### CODE REVIEW

**Review by sonalmahajan15 — CHANGES_REQUESTED** [review]
Nice! Could you also add support for `iter.Seq`? The golden test is reporting internal errors.

**Comment by yuxincs** [comment]
> ```diff
> AppendSeq
> ```

This seems to be a separate issue we should handle, will do that in a follow-up PR :)

**Comment by yuxincs** [comment]
> > Nice! Could you also add support for `iter.Seq`? The golden test is reporting internal errors.
> 
> This seems to be a separate issue we should handle, will do that in a follow-up PR :)

Done in #288

**Review by sonalmahajan15 — APPROVED** [review]
Awesome. Good to land after the needed support added in #288 .

**Pull request merged**
