### PR TITLE
new x/tools dep to work with newer go1.23.0

### PR DESCRIPTION
**Pull request by jayalane**
As per issue https://github.com/uber-go/nilaway/issues/269 this PR updates go.mod/go.sum to work with go 1.23.0

### CODE REVIEW

**Comment by arnested** [comment]
I experience the same problem and this fixes it for me as well.

**Comment by chlanejayasinha** [comment]
Signed.  (I had signed it at the time but I put in a different email that I thought was associated to the account but wasn't; just now I signed it with an email that was associated to the account).

**Comment by chlanejayasinha** [comment]
The failing test looks like it succeeded but then failed to connect back to api.github.com with the results.  403.  a

**Review by yuxincs — APPROVED** [review]

**Comment by yuxincs** [comment]
Thanks @jayalane!

**Pull request merged**
